#!/usr/bin/env node

var Parser = require('jison').Parser;

var grammar = [];

process.stdin.setEncoding('utf8');

process.stdin.on('readable', function() {
  var chunk = process.stdin.read();
  if (chunk !== null) {
    grammar.push(chunk);
  }
});

process.stdin.on('end', function() {
  var parser = new Parser(grammar.join(""));
  
  process.stdout.write(parser.generate());
});
